name: "Spellcheck"
description: Check for spelling mistakes
inputs:
  GITHUB_TOKEN:
    description: "GitHub token"
    default: ""
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get Changed Files
      id: changed-files
      uses: tj-actions/changed-files@v40
      with:
        files: |
          **/*.md

    - name: Check if any Markdown file was changed
      if: steps.changed-files.outputs.any_changed  == 'false'
      shell: bash
      run: |
        echo "No Markdown files were changed"
        exit 0

    - name: Setup Environment
      if: steps.changed-files.outputs.any_changed  == 'true'
      shell: bash
      run: |
        wget -O config-action.zip -q https://github.com/open-education-hub/actions/archive/refs/heads/main.zip
        unzip -q config-action.zip -d config-action
        [ ! -f ".spellcheck.yml" ] && mv config-action/actions-main/spellcheck/config/spellcheck.yml .spellcheck.yml
        [ ! -f ".acronyms.txt" ] && mv config-action/actions-main/spellcheck/config/acronyms.txt .acronyms.txt
        [ ! -f ".other_names.txt" ] && mv config-action/actions-main/spellcheck/config/other_names.txt .other_names.txt
        [ ! -f ".people_names.txt" ] && mv config-action/actions-main/spellcheck/config/people_names.txt .people_names.txt
        [ ! -f ".technical.txt" ] && mv config-action/actions-main/spellcheck/config/technical.txt .technical.txt
        [ ! -f ".wordlist.txt" ] && mv config-action/actions-main/spellcheck/config/wordlist.txt .wordlist.txt

    - name: Spellcheck
      if: steps.changed-files.outputs.any_changed  == 'true'
      uses: rojopolis/spellcheck-github-actions@v0
      with:
        config_path: .spellcheck.yml
        source_files: ${{ steps.changed-files.outputs.all_changed_files }}
        task_name: Markdown
